name: Build Jar Only

on:
  workflow_dispatch:
    inputs:
      mod_version:
        description: 'Mod Version to Build (e.g. 1.0.1)'
        required: true
        default: '1.0.1'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: gradle

    - name: Update gradle.properties Version
      run: |
        sed -i "s/^mod_version = .*/mod_version = ${{ inputs.mod_version }}/" gradle.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build --no-daemon

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: wrapperitas-${{ inputs.mod_version }}
        path: build/libs/*.jar
